# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/nhsuk.base-application.UnitTests'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/nhsuk.base-application'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'nhsuk-development(07748954-52d6-46ce-95e6-2701bfc715b4)'
    ScriptType: 'InlineScript'
    Inline: |
      Start-Process powershell -ArgumentList "-NoProfile", "-NonInteractive", "-NoExit", {
          dotnet run
      }
    FailOnStandardError: true
    preferredAzurePowerShellVersion: '3.1.0'
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/nhsuk.base-application'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- task: CmdLine@2
  inputs:
    script: npm install && npm test
    workingDirectory: '$(System.DefaultWorkingDirectory)/AcceptanceTests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/src/nhsuk.base-application'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'nhsuk-development(07748954-52d6-46ce-95e6-2701bfc715b4)'
    appType: 'webApp'
    WebAppName: 'nhsuk-base-application-dev-uks'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'