version: '3'

services:
  base-application:
    image: base-app
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        nuget_pat: ${NUGET_PAT}
    ports:
      - 5000:5000
    volumes:
      - './:/app'
      - /src/nhsuk.base-application/node_modules
