version: '3'

services:
  nhsuk.base-application:
    image: nhsuk.base-application
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        nuget_pat: ${NUGET_PAT}
    ports:
      - 8080:80
